# This is convenient for default reporting,
# and a footgun when you want to work with another file; use -n then.
-f pta.journal

[alias]

c = help commands

# show a balance sheet demonstrating a balanced accounting equation
bse1 = bse --infer-equity --alias '/^(revenues|expenses)/=equity:retained' -t

# show revenue by sponsor tier
tiers = bal revenue -YAT --pivot acct:tier --title ''
